name: Build and Check

on:
  push:
    branches:
      - main  # Change to the branch you want this to run on
  pull_request:
    branches:
      - main  # Change to the branch you want this to run on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies (if needed, e.g., build tools)
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Make the run_make.sh script executable
      - name: Make script executable
        run: chmod +x ./check_make.sh

      # Run the script to execute make
      - name: Run make
        run: ./check_make.sh

      # Optionally, you can fail the build on errors
      - name: Fail the build if make fails
        if: ${{ failure() }}
        run: exit 1
